### PR TITLE
Add i18n support (version 2.1)

### PR DESCRIPTION
**Pull request by ko31**
I'd like to use this plugin in Japanese, so I added support for internationalization.

Once this has been merged, we'll be able to translate it on the following WordPress page.
https://translate.wordpress.org/projects/wp-plugins/star-cloudprnt-for-woocommerce/

By the way, the following is an example of Japanese translation in my development environment.

i18n-sample1

i18n-sample2

i18n-sample3

### CODE REVIEW

**Comment by Lozrus** [comment]
@ko31 fantastic, thank you. I'm just reviewing the changes and will pull this in today. Really big thanks for a very valuable PR.

**Review by Lozrus — APPROVED** [review]
Looks good!

**Comment by Lozrus** [comment]
@ko31 Thanks for this. I think your branch was day or two behind ours, so I had to leave out a few changes to the item list printing code. But I'll re-implement these today in the new code structure - it's just small stuff.

**Comment by ko31** [comment]
@Lozrus 
I'm sorry about that. You are right, my branch was not up to date.
Thank you for helping.:pray:

**Comment by Lozrus** [comment]
@ko31 No problem at all, the differences are easy for me to fix by hand, and your PR is extremely valuable. It's very easy to do, because the 2.1 branch is really a moving target now.

**Pull request merged**
