### PR TITLE
I18n support

### PR DESCRIPTION
**Pull request by ko31**
I'd like to use this plugin in Japanese, so I added support for internationalization.

Once this has been merged, we'll be able to translate it on the following WordPress page.
https://translate.wordpress.org/projects/wp-plugins/star-cloudprnt-for-woocommerce/

By the way, the following is an example of Japanese translation in my development environment.

sample1

sample2

sample3

### CODE REVIEW

**Comment by Lozrus** [comment]
@ko31 

This is great, thank you! We will 100% ensure that the 2.1.x and later releases are translatable, your results looks really good.
My only concern, is that the version 2.1 branch is already very different to 2.0/master, so I think that I will not be able to merge in your pull request directly, or maybe only some parts of it (as usual, the order-handler.php file is the most heavily modified).

Anyway, I will test here to see which parts can be safely merged (I guess the settings pages at least) and which part I need to re-implement manually. Unless you are willing to submit a patch against the current 2.1 branch directly?

**Comment by ko31** [comment]
Oh, I've forgotten to consider the version 2.1 branch... :sweat_smile:

I'd like to submit another new pull request for that branch later, so could you please ignore this pull request?

**Comment by Lozrus** [comment]
@ko31 
If you're happy to submit a patch for the 2.1 branch then that is perfect :-)
I'll hold off pushing any more code changes for a little while (it's good for me to focus on the documentation anyway) because a lot of the changes are structural and likely to break merging. Thanks for your very helpful contribution.

**Comment by ko31** [comment]
@Lozrus 
I submitted a patch for the 2.1 branch.
https://github.com/star-micronics/star-cloudprnt-for-woocommerce/pull/9

Could you please close this pull request?

**Pull request closed without merging**
